### ISSUE TITLE
Failed to load the data-explorer package

### ISSUE THREAD

**Issue by cchlanger** [BenRussert/data-explorer#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Ubuntu 16.04.5
**Thrown From**: [data-explorer](https://github.com/BenRussert/data-explorer) package 0.3.1

### Stack Trace

Failed to load the data-explorer package

```
At Cannot find module '@blueprintjs/select'

Error: Cannot find module '@blueprintjs/select'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:154364)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145671)
    at /packages/data-explorer/node_modules/@nteract/transform-dataresource/lib/VizControls.js:20:15)
    at /packages/data-explorer/node_modules/@nteract/transform-dataresource/lib/VizControls.js:391:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145671)
    at /packages/data-explorer/node_modules/@nteract/transform-dataresource/lib/index.js:48:43)
    at /packages/data-explorer/node_modules/@nteract/transform-dataresource/lib/index.js:495:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145671)
    at /packages/data-explorer/lib/common.js:33:2)
    at /packages/data-explorer/lib/common.js:11:76)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Commands

```
```

### Non-Core Packages

```
data-explorer 0.3.1 
Hydrogen 2.6.0 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.7 
```

**Comment by Lokdal** [comment]
I have the same problem when I try to install data-explorer from atom.

Atom 1.32.0 x64
Windows 10 x64

Non-Core Packages
data-explorer 0.3.1
Hydrogen 2.6.0
Hydrogen-python 0.0.7
ide-python 1.0.0
atom-ide-ui 0.13
autocomplete-python 1.10.12
comment 0.6.1

**Comment by BenRussert** [comment]
```
Error: Cannot find module '@blueprintjs/select'
```
Looks like an issue with the latest release of `@nteract/transform-dataresource`. 

I'll look at this tonight. cc/ @rgbkrk

**Comment by rgbkrk** [comment]
Ah, looks like `@blueprintjs/select` needs to be added as a dep on the data explorer.

cc @emeeks

**Comment by mcr-ksh** [comment]
same here

**Comment by emeeks** [comment]
Should be fixed with #3566 unless it's something deeper than that.

**Comment by mcr-ksh** [comment]
> Should be fixed with #3566 unless it's something deeper than that.

how can I get the fix? can't find any new commits or a link to the #3566

**Comment by rgbkrk** [comment]
I'll get the packages shipped today.

**Comment by hasanOryx** [comment]
@rgbkrk 
I installed today the `apm install hydrogen data-explorer` a atom, and still getting the same error :(

<img width="350" alt="dv" src="https://user-images.githubusercontent.com/26045838/47904127-c0be7200-de95-11e8-9157-9089134ef0cd.PNG">

**Comment by rgbkrk** [comment]
We just shipped a new release of the data explorer that includes it, it's an alpha though. I'll make a PR.

**Comment by rjczanikcorp** [comment]
Still getting this same error after installing latest version of data-explorer.
